I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 231, in script
    $ ending += 1;
  File "game/script.rpy", line 231, in <module>
    $ ending += 1;
NameError: name 'ending' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 231, in script
    $ ending += 1;
  File "C:\Users\brens\OneDrive\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\brens\OneDrive\Desktop\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 231, in <module>
    $ ending += 1;
NameError: name 'ending' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
Falsaritas: Perfect Order 1.0
Thu Dec 12 23:53:02 2024
